USE database bi_dev_ods;
create schema PRONTO;

create table PRONTO."system_table"
(   "Entity_id" varchar(3) NULL,
	"row_id" bigint NULL,
	"sys_tbl_type" varchar(2) NULL,
	"sys_tbl_code" varchar(10) NULL,
	"tbl_sales_mtd" decimal(12, 2) NULL,
	"tbl_sales_ytd" decimal(12, 2) NULL,
	"sys_tbl_sales_ly" decimal(12, 2) NULL,
	"sys_description" varchar(30) NULL,
	"sys_money_value" decimal(19, 6) NULL,
	"date_last_change" date NULL,
	"sys_tbl_alpha_1" varchar(10) NULL,
	"sys_tbl_alpha_2" varchar(4) NULL,
	"sys_tbl_alpha_3" varchar(4) NULL,
	"tbl_alpha_4_1" varchar(1) NULL,
	"tbl_alpha_4_2" varchar(1) NULL,
	"tbl_alpha_4_3" varchar(1) NULL,
	"tbl_alpha_4_4" varchar(1) NULL,
	"tbl_inactive_date" datetime NULL,
	"warning_days" smallint NULL,
	"tbl_user_only_date1" datetime NULL,
	"tbl_user_only_date2" datetime NULL,
	"user_only_alpha20_1" varchar(20) NULL,
	"user_only_alpha20_2" varchar(20) NULL,
	"user_only_alpha4_1" varchar(4) NULL,
	"user_only_alpha4_2" varchar(4) NULL,
	"user_only_alpha4_3" varchar(4) NULL,
	"user_only_alpha4_4" varchar(4) NULL,
	"tbl_user_only_num1" decimal(19, 4) NULL,
	"tbl_user_only_num2" decimal(19, 4) NULL,
	"tbl_user_only_num3" decimal(19, 4) NULL,
	"tbl_user_only_num4" decimal(19, 4) NULL,
	"sys_tbl_spare_date1" datetime NULL,
	"sys_tbl_spare_date2" datetime NULL,
	"tbl_spare_alpha20_1" varchar(20) NULL,
	"tbl_spare_alpha20_2" varchar(20) NULL,
	"tbl_spare_alpha4_1" varchar(4) NULL,
	"tbl_spare_alpha4_2" varchar(4) NULL,
	"tbl_spare_alpha4_3" varchar(4) NULL,
	"tbl_spare_alpha4_4" varchar(4) NULL,
	"sys_tbl_spare_num1" decimal(19, 4) NULL,
	"sys_tbl_spare_num2" decimal(19, 4) NULL,
	"sys_tbl_spare_num3" decimal(19, 4) NULL,
	"sys_tbl_spare_num4" decimal(19, 4) NULL
)